# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jedi Council' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jedi Council
  pod 'Kingfisher', '5.7.0', :inhibit_warnings => true
  pod 'Moya', '~> 13.0', :inhibit_warnings => true
end
